FROM node:18-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

# Copia código do frontend e arquivos necessários para build
COPY . .

# Args para injetar variáveis no build do Vite
ARG VITE_BACKEND_URL

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY scripts/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80