# Configuração OTIMIZADA para EasyPanel - Deploy Rápido
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
      cache_from:
        - node:18-alpine
    
    ports:
      - "3001:3001"
    
    environment:
      NODE_ENV: production
      PORT: 3001
      CORS_ALLOW_ALL: "true"
      # Suas variáveis de ambiente
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-https://evolution.nowhats.com.br}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-429683C4C977415CAAFCCE10F7D57E11}
      SUPABASE_URL: ${SUPABASE_URL:-https://soyitaocrqxwkgssrcah.supabase.co}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-https://evochat.nowhats.com.br}
    
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge