# CONFIGURAÇÃO MÍNIMA PARA EASYPANEL - SOLUÇÃO URGENTE
name: chatnegocios-minimal
services:
  - type: app
    data:
      projectName: chatnegocios
      serviceName: app
      source:
        type: github
        repo: seu-usuario/chatnegocios
        branch: main
      build:
        type: dockerfile
        dockerfile: Dockerfile.simple
      env:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: "3001"
        - key: EVOLUTION_API_URL
          value: "https://evolution.nowhats.com.br"
        - key: EVOLUTION_API_KEY
          value: "429683C4C977415CAAFCCE10F7D57E11"
      ports:
        - published: 80
          target: 3001