# Configuração otimizada para EasyPanel
name: chatnegocios
services:
  - type: app
    data:
      projectName: chatnegocios
      serviceName: app
      source:
        type: github
        repo: seu-usuario/chatnegocios
        branch: main
      build:
        type: dockerfile
        dockerfile: Dockerfile
      deploy:
        replicas: 1
        strategy: RollingUpdate
        restartPolicy: unless-stopped
      env:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: "3001"
        - key: CORS_ALLOW_ALL
          value: "true"
        # Adicione suas variáveis de ambiente aqui
        - key: EVOLUTION_API_URL
          value: "${EVOLUTION_API_URL}"
        - key: EVOLUTION_API_KEY
          value: "${EVOLUTION_API_KEY}"
        - key: SUPABASE_URL
          value: "${SUPABASE_URL}"
        - key: SUPABASE_SERVICE_ROLE_KEY
          value: "${SUPABASE_SERVICE_ROLE_KEY}"
      ports:
        - published: 80
          target: 3001
      healthcheck:
        test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        startPeriod: 40s
      resources:
        limits:
          memory: 512M
          cpuQuota: 0.5
        reservations:
          memory: 256M
          cpuQuota: 0.25