version: '3.8'
services:
  chatnegocios_backend:
    image: chatnegocios-backend:latest
    container_name: chatnegocios_backend
    environment:
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "3001:3001"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatnegocios-backend.rule=Host(`${CHATNEGOCIOS_API_DOMAIN}`)
      - traefik.http.routers.chatnegocios-backend.entrypoints=websecure
      - traefik.http.routers.chatnegocios-backend.tls=true
      - traefik.http.routers.chatnegocios-backend.tls.certresolver=le
      - traefik.http.services.chatnegocios-backend.loadbalancer.server.port=3001
    networks:
      - proxy
      - app_net

  chatnegocios_frontend:
    image: chatnegocios-frontend:latest
    container_name: chatnegocios_frontend
    # Frontend chama Evolution e Backend pelo host
    ports:
      - "8081:80"
    depends_on:
      - chatnegocios_backend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatnegocios.rule=Host(`${CHATNEGOCIOS_DOMAIN}`)
      - traefik.http.routers.chatnegocios.entrypoints=websecure
      - traefik.http.routers.chatnegocios.tls=true
      - traefik.http.routers.chatnegocios.tls.certresolver=le
      - traefik.http.services.chatnegocios.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
  app_net:
    external: true