version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - evo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  evolution-api:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      APP_PORT: ${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"

volumes:
  evo_pgdata: